server:
  port: 8080

spring:
  application:
    name: resalemanagement
  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5432/resalemanagement
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect